CREATE DATABASE music_shop;
USE `music_shop`;

DROP TABLE IF EXISTS `Songs`;
CREATE TABLE Songs (
  SongID INT NOT NULL AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  ArtistID INT NOT NULL,
  Genre VARCHAR(255),
  ReleaseYear INT,
  PRIMARY KEY (SongID),
  FOREIGN KEY (ArtistID) REFERENCES Artists(ArtistID)
);

DROP TABLE IF EXISTS `Artists`;
CREATE TABLE Artists (
  ArtistID INT NOT NULL AUTO_INCREMENT,
  Name VARCHAR(255) NOT NULL,
  Country VARCHAR(255),
  PRIMARY KEY (ArtistID)
);

DROP TABLE IF EXISTS `Albums`;
CREATE TABLE Albums (
  AlbumID INT NOT NULL AUTO_INCREMENT,
  Title VARCHAR(255) NOT NULL,
  ArtistID INT NOT NULL,
  ReleaseYear INT,
  PRIMARY KEY (AlbumID),
  FOREIGN KEY (ArtistID) REFERENCES Artists(ArtistID)
);






